### ISSUE TITLE
why don't use rawcam output yuv

### ISSUE THREAD

**Issue by TongleiJin** [6by9/raspiraw#32] opened 2019-11-27 02:04 UTC
Now the project output yuv by isp component, why not use rawcam output yuv directly? I did see "MMAL_ENCODING_I420" likes in "mmal_encodeings.h".  @6by9

**Comment by 6by9** [comment] 2019-11-27 09:57
Closing as a duplicate of #31

**Closed by 6by9** 2019-11-27 09:57 UTC
